apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/api/auth/?(.*)"
        backend:
          service:
            name: auth-service
            port: 
              number: 3000
